#/appspec.yml
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/cardera
    overwrite: yes
permissions:
  - object: /
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: /scripts/stop.sh
      runas: root
      timeout: 60
  ApplicationStart:
    - location: /scripts/deploy.sh
      runas: root
      timeout: 60